# Builtin Class Variant (defined manually)
import ../../ffi
import ../../api

type
  Variant* = object
    opaque: array[variantSize, byte]

# Enums
type
  Type* {.size: sizeof(cint).} = enum
    vtyNil = GDEXTENSION_VARIANT_TYPE_NIL,
    vtyBool = GDEXTENSION_VARIANT_TYPE_BOOL,
    vtyInt = GDEXTENSION_VARIANT_TYPE_INT,
    vtyFloat = GDEXTENSION_VARIANT_TYPE_FLOAT,
    vtyString = GDEXTENSION_VARIANT_TYPE_STRING,
    vtyVector2 = GDEXTENSION_VARIANT_TYPE_VECTOR2,
    vtyVector2i = GDEXTENSION_VARIANT_TYPE_VECTOR2I,
    vtyRect2 = GDEXTENSION_VARIANT_TYPE_RECT2,
    vtyRect2i = GDEXTENSION_VARIANT_TYPE_RECT2I,
    vtyVector3 = GDEXTENSION_VARIANT_TYPE_VECTOR3,
    vtyVector3i = GDEXTENSION_VARIANT_TYPE_VECTOR3I,
    vtyTransform2d = GDEXTENSION_VARIANT_TYPE_TRANSFORM2D,
    vtyVector4 = GDEXTENSION_VARIANT_TYPE_VECTOR4,
    vtyVector4i = GDEXTENSION_VARIANT_TYPE_VECTOR4I,
    vtyPlane = GDEXTENSION_VARIANT_TYPE_PLANE,
    vtyQuaternion = GDEXTENSION_VARIANT_TYPE_QUATERNION,
    vtyAABB = GDEXTENSION_VARIANT_TYPE_AABB,
    vtyBasis = GDEXTENSION_VARIANT_TYPE_BASIS,
    vtyTransform3D = GDEXTENSION_VARIANT_TYPE_TRANSFORM3D,
    vtyProjection = GDEXTENSION_VARIANT_TYPE_PROJECTION,
    vtyColor = GDEXTENSION_VARIANT_TYPE_COLOR,
    vtyStringName = GDEXTENSION_VARIANT_TYPE_STRING_NAME,
    vtyNodePath = GDEXTENSION_VARIANT_TYPE_NODE_PATH,
    vtyRID = GDEXTENSION_VARIANT_TYPE_RID,
    vtyObject = GDEXTENSION_VARIANT_TYPE_OBJECT,
    vtyCallable = GDEXTENSION_VARIANT_TYPE_CALLABLE,
    vtySignal = GDEXTENSION_VARIANT_TYPE_SIGNAL,
    vtyDictionary = GDEXTENSION_VARIANT_TYPE_DICTIONARY,
    vtyArray = GDEXTENSION_VARIANT_TYPE_ARRAY,
    vtyPackedByteArray = GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY,
    vtyPackedInt32Array = GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY,
    vtyPackedInt64Array = GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY,
    vtyPackedFloat32Array = GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY,
    vtyPackedFloat64Array = GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY,
    vtyPackedStringArray = GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY,
    vtyPackedVector2Array = GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY,
    vtyPackedVector3Array = GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY,
    vtyPackedColorArray = GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY

  CallErrorType* {.size: sizeof(cint).} = enum
    vceOk = GDEXTENSION_CALL_OK,
    vceInvalidMethod = GDEXTENSION_CALL_ERROR_INVALID_METHOD,
    vceInvalidArgument = GDEXTENSION_CALL_ERROR_INVALID_ARGUMENT,
    vceTooManyArguments = GDEXTENSION_CALL_ERROR_TOO_MANY_ARGUMENTS,
    vceTooFewArguments = GDEXTENSION_CALL_ERROR_TOO_FEW_ARGUMENTS,
    vceInstanceIsNull = GDEXTENSION_CALL_ERROR_INSTANCE_IS_NULL,
    vceMethodNotConst = GDEXTENSION_CALL_ERROR_METHOD_NOT_CONST

func variantTypeId*(_: typedesc[Variant]): GDExtensionVariantType =
  GDEXTENSION_VARIANT_TYPE_NIL